### ISSUE TITLE
Make 'Invite User' more easily accessible

### ISSUE THREAD

**Issue by michkwt** [unee-t/frontend#197]
<img width="242" alt="screen shot 2018-04-09 at 1 56 22 pm" src="https://user-images.githubusercontent.com/38183796/38481522-d89a6c16-3bfd-11e8-9b5a-39815949c600.png"> 
<img width="263" alt="screen shot 2018-04-09 at 1 56 04 pm" src="https://user-images.githubusercontent.com/38183796/38481572-07261efe-3bfe-11e8-8226-8037389d31aa.png"> 

The document icon is replaced with Invite User icon. Adding of Document is still available with the "+" option.

Invite User icon: 
[invite user icon.svg.zip](https://github.com/unee-t/frontend/files/1888913/invite.user.icon.svg.zip)

**Comment by franck-boullier** [comment]
I like it!

**Comment by franck-boullier** [comment]
Tapping on the icon should open the "invite user to a case" dialogue box
![image](https://user-images.githubusercontent.com/31331637/38482465-fc5da704-3c01-11e8-94f5-7606b8b382dd.png)

**Comment by kaihendry** [comment]
First the people who are already listed there are already somehow associated with the property correct? I find it a little strange they have to be invited at all.

The real confusion in my mind is what happens when you type a name or email that's not on the system in that top input. First I don't expect it to filter the people who are already associated. It should be a more clean cut way of inviting participation of someone not on the system.

**Comment by franck-boullier** [comment]
@kaihendry "First the people who are already listed there are already somehow associated with the property correct" Yes they are but we still need to:
- associate these person to this specific case: this is what this invitation process is about, invite a user to a specific case.
- make it easy to add more user to the case (and by extension to the unit too)

"The real confusion in my mind is what happens when you type a name or email that's not on the system in that top input." I totally agree with you and we are in the process of redesigning this window to make it clearer (remove the search altogether).

**Comment by kaihendry** [comment]
Not sure why a new bug was created but https://github.com/unee-t/frontend/issues/198 seems relevant. ;)

**Comment by franck-boullier** [comment]
@michkwt can you also add the image file for the new icon there so it's available

**Comment by franck-boullier** [comment]
@kaihendry 

> Not sure why a new bug was created but #198 seems relevant. ;)

#198 is definitely relevant for that!
This is a different bug though as #198 will have impact each time the invitation mechanism is triggered.
This bug is about replacing an icon and make sure that this icon call the invitation procedure (when #198 is done, the invitation will be modified)

**Comment by sophieyang0813** [comment]
<img width="317" alt="screen shot 2018-07-03 at 11 16 11 am" src="https://user-images.githubusercontent.com/25441733/42197434-61e68da2-7eb5-11e8-94eb-6c1b9534cced.png">
<img width="298" alt="screen shot 2018-07-03 at 11 14 23 am" src="https://user-images.githubusercontent.com/25441733/42197436-622c49be-7eb5-11e8-8053-98970925fafa.png">
@michkwt @kiatlim Good morning! The above images show where the design stands as of today. Would you like an invite user icon next to the arrow? Where would a camera button be at? A tilted square button that contains options and a message sent button look clustered.

**Comment by kiatlim** [comment]
@sophieyang0813 morning! the idea was that when the user is focused on the message field, their intention is to send the message. When they are out of focus and on the conversation, they would like to invite / upload something. 

You can't send an empty message anyway so the icon is changed to send only when focus on message field. That's the idea behind, what do you think?

**Comment by franck-boullier** [comment]
> Where would a camera button be at? 

@sophieyang0813 I think the idea is to have that accessible via the '+' on the left of the 'type your response' element
@kiatlim comments?

**Comment by kaihendry** [comment]
Just a few comments, feel free to ignore.

IIUC the basis of this issue to make the action of **inviting another user more accessible**. The button on the bottom bar imo is a bad approach:
* pollutes/confuses the bottom bar which should be solely for input
* creates another way / flow to do something that needs to considered
* creates cognitive load, since if i want to invite a user, i have now two ways of doing it. which one do I choose?

I see the problem making invites easier. For me the invite component is problematic because:
* it's nested in moreinfo
* it's a modal (i hate modals, please please don't use them)
* moreinfo is problematic since the top bar is not fixed on my ios device, also confusingly be presented as More in the solution line too
* /case/1235/moreinfo/invite could be just /case/1235/invite

Proposal:
Instead of Case #12345 | Priority: P3 | More info

    Invite | More info

Centered and split in the middle.


Put case id in "bondi blue" top bar and the priority as I've mentioned before seems like noise to me.
I don't care for the "More" in Solution bar.

**Comment by kiatlim** [comment]
@kaihendry @sophieyang0813 we have done some discussion on this and will go ahead with what you propose. @michkwt is going to come up with some visual so that @sophieyang0813 can implement this clearer. 

For the record, agree that the bottom part will be solely used for messaging input. The bottom will just have this:
+ _______________ >

**Comment by michkwt** [comment]
<img width="266" alt="screen shot 2018-07-06 at 3 09 51 am" src="https://user-images.githubusercontent.com/38183796/42342928-1ddf8700-80ca-11e8-864e-eb309ef2161c.png">

Here's the new visual for case conversation. if all good, i will update invision and provide the SVG file for the icons here.

**Comment by franck-boullier** [comment]
Thanks @michkwt I like the latest design a lot kuddos to @kaihendry for suggesting this improvement!

@michkwt can you make sure that this latest design is used in the Video explainer too?

**Comment by michkwt** [comment]
![unee-t user flow - case conversation](https://user-images.githubusercontent.com/38183796/42367651-7eb28402-8137-11e8-855e-4728ca1e0fef.jpg)
https://invis.io/9NMND0SGBR7#/299164183_5-1-0_Create_Case_-_Case_Detail-Invite_People
SVG files: 
[SVG icons for case conversation.zip](https://github.com/unee-t/frontend/files/2169560/SVG.icons.for.case.conversation.zip)

**Comment by nbiton** [comment]
Can we user this icon instead? 
https://material.io/tools/icons/?icon=person_add&style=outline

![screenshot from 2018-07-10 18-39-27](https://user-images.githubusercontent.com/2662819/42505215-b5bfb5c8-8470-11e8-8bf8-5bd14db53340.png)

It looks almost the same, matches the style of all of our other icons, and most importantly, doesn't require an additional external asset (it's a part of our font icon library)

**Comment by nbiton** [comment]
> Can we use this icon instead?
@michkwt @franck-boullier @kiatlim

**Comment by franck-boullier** [comment]
> Can we use this icon instead?

Yes you can use that icon

**Comment by franck-boullier** [comment]
Done
