### ISSUE TITLE
automated invitation - invited user is not visible after invitation

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#253]
# The Test:
- Go to an existing case
- invite a new user

# Test result:
## for the invitor:
- no error messages: PASSED
- confirmation message that the invitation has been sent: PASSED
- Once confirmation window is closed, the new invited user appears in the list of invited user: FAILED
In order to see the invited user, I have to force refresh the page.

**Comment by nbiton** [comment]
This is a really tricky issue... I see that it DOES work about 3 out of 4 invitations, but pretty inconsistent. I think there's a race condition with the way it is updated on Mongo. Locally, since it's much faster, it works 100% of the time. It's going to take me some time to figure out why it fails occasionally

**Comment by franck-boullier** [comment]
This has been fixed
