### ISSUE TITLE
Add option for user to opt-out from various types of email notifications

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#303]
This will allow the user to pick and choose which email notifications will be sent to him.
The feature requires implementation of the following:
* New view with UI to modify every one of the 3 possible settings (1 for each notification type)
* Check setting every time before sending a notification to a user
* Create a migration to create all new settings on all users with a default value of 'true' (notifications enabled)
* Add a link to the bottom of each email template to quickly direct the user to the settings view to unsubscribe

**Comment by franck-boullier** [comment]
Clarifying the scope of the issue: this is so that the user can opt out from notification via emails.

We will have several other types of notification in the near future:
- 'in app' notification
- SMS (?)
And we will need to be able to manage each separately.

@kiatlim this is the current interface we have:
Can you have a look at this a let us know your thoughts on how we can best to that?
![image](https://user-images.githubusercontent.com/31331637/41753610-0048a89e-7601-11e8-9aa3-f60fddec9f6a.png)
and
![image](https://user-images.githubusercontent.com/31331637/41753622-12eb1f68-7601-11e8-8ffb-3df81a4e4b4a.png)
