### ISSUE TITLE
Discrepancy between Mongo Collection for units and unit creation form

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#306]
In the Mongo Database, we have the capability to store the following information in the `unitMetaData` collection:
- _id
- bzId
- bzName
- city
- country
- displayName
- state
- streetAddress
- zipCode

The form we are creating for unit creation (https://projects.invisionapp.com/d/main#/console/12250377/299136062/preview) has the following fields:
- Unit Name
- Additional Description
- Address
- City
- Country
- State/Province
- ZIP/Postal Code

We need to be able to map all the fields in the form to the mongo collection:
- Unit Name -> displayName
- Additional Description -> ??? (missing)
- Address -> streetAddress
- City -> city
- state
- Country -> country
- State/Province -> state
- ZIP/Postal Code -> zipCode

**Comment by kaihendry** [comment]
iirc @sebdeckers was talking about this. We should get this standardised rock solid. I highly recommend they map to https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-address-line1 so that the browser can help with autofill.

I actually not 100% sure which table addresses are currently defined in.

**Comment by franck-boullier** [comment]
< map to https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-address-line1 so that the browser can help with autofill

I completely agree with that (I was looking for that link earlier, thanks!)

**Comment by franck-boullier** [comment]
This has been fixed in the June 25th release: Mongo collection have been updated
