### ISSUE TITLE
leonel@example.com cannot be logged in

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#348]
This affects both dev/demo

![ezgif com-optimize 3](https://user-images.githubusercontent.com/17175484/42195213-59ce90c0-7eaa-11e8-8743-b94e44144d8b.gif)

Since we have this on automated schedule : last success was 2nd July 4:00 AM.
Login issue was detected on 3rd July 4:00 AM nightly test run, and confirmed subsequently.

The console logs are as below 
![screen shot 2018-07-03 at 10 18 41 am](https://user-images.githubusercontent.com/17175484/42195260-9b81256e-7eaa-11e8-90f1-5138e3c36001.png)
![screen shot 2018-07-03 at 10 18 58 am](https://user-images.githubusercontent.com/17175484/42195262-9d2198f4-7eaa-11e8-9c4a-2d01c102a705.png)

**Dev / Demo Account tested**
In general all accounts give "User not found [403]" with the exception of leonel

- leonel@example.com ( Incorrect Password [403] for demo )
- marley@example.com
- michael@example.com
- sabrina@example.com
- celeste@example.com
- jocelyn@example.com
- marina@example.com
- regina@example.com
- marvin@example.com
- lawrence@example.com
- anabelle@example.com
- management.co@example.com

**Comment by kaihendry** [comment]
Can confirm https://media.dev.unee-t.com/2018-07-03/leonel-mongo-password.mp4

**Comment by franck-boullier** [comment]
All logins for demo user @example.com have been changed to @mailinator.com
example:
- leonel@example.com -> leonel@mailinator.com
- marley@example.com -> marley@mailinator.com
- etc...

This has been documented on the [documentation website](https://documentation.unee-t.com/2018/03/01/introduction-to-the-demo-environment/) and on this [Github issue](https://github.com/unee-t/bz-database/issues/75).

**Comment by kaihendry** [comment]
How come I could login as [leonel@example.com on https://dashboard.dev.unee-t.com/](https://media.dev.unee-t.com/2018-07-03/leonel-mongo-password.mp4) ?

I think documentation should be perhaps merged into https://github.com/unee-t/frontend/wiki
This is only relevant for development/testing right? Not for customers.

**Comment by franck-boullier** [comment]
> How come I could login as leonel@example.com on https://dashboard.dev.unee-t.com/ ?

This is only specific to the DEV/Staging which is NOT where we should conduct demos and UAT -> these should be done on case.demo and dashboard.demo respectively

Demo are accessible to prospect customer to give them a sense of how it works.
This is also why we have articles like 'How to create a case' in the documentation so that people who have not signed up and are just trying to decide if this might be a good idea to create an account can see how easy and simple it is to work with Unee-T

Dev/Staging is only for developer so there might be a need to create a parallel documentation in the GH Wiki for these guys (different need and different content as the questions are very different for dev than for most standard users)
