### ISSUE TITLE
Monitor level of spam on support mailbox

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#353]
Before we merge changes in PR #349 in production, we need to have a few user feedbacks on wether they prefer support via email vs support via forms (I must admit that I am biaised here: I REALLY don't like/borderline hate support via email and very much prefer to fill a form)

We also need to monitor the level of spam generated by having the support email address so easily accessible for spambot to scrap and abuse...

**Comment by franck-boullier** [comment]
@kiatlim your input on this is welcomed: @kaihendry is strongly in favor of email vs form and I have a completely opposite view on that: I very much prefer a form: we need the input of the UI/UX design expert here 😅

**Comment by franck-boullier** [comment]
@kaihendry 
I must say I have been traumatized by spambots in my previous companies: it is an absolute nightmare to have to shift through 200 spam emails everyday to find the 2 or 3 legit emails that were sent to you...
We got badly burnt and I want to avoid that at all costs

interesting read on how to implement basic protection against spambot:
- http://www.bronze-age.com/nospam/
- https://stackoverflow.com/questions/3624667/how-to-spamproof-a-mailto-link
- https://www.campaignmonitor.com/blog/email-marketing/2013/06/tip-avoid-using-mailto-links-in-html-email/

I'd suggest that we review https://github.com/unee-t/frontend/blob/master/imports/ui/side-menu/side-menu.jsx#L85 before we go live with this change...
- http://websitehelpers.com/spam/

**Comment by kaihendry** [comment]
Gmail has a spam filter. Helpscout has a spam filter. When it's a problem (and I don't see it being one) we can act.

Before that, we shouldn't make customers jump hoops.

**Comment by franck-boullier** [comment]
I hear what you are saying @kaihendry but I still profoundly disagree on this:
a simple and well conceived form is not "make customers jump hoops"

Personally, each time I see a service/website which uses a 'mailto' function as contact mechanism I consider this as hacky, ugly and my level of trust in the quality of their technology decreases massively: in my mind I think "they stilll use this mailto thing from 1990 ?!?! Wow! that IS bad...".

I can't think of any major Internet or software company which uses mailto as a primary mode of contact  method too (Google, paypal, YouTube, AWS, Msft, Github, Slack, etc...): there probably is a reason for that...

I understand that I am not a typical user though and that this is only my own personal reaction/preference -> this is why I think we need a UX/UI expert's point of view on that...

**Comment by kaihendry** [comment]
Take out a stop watch. Time how long it takes to provide a support query coming into helpscout between the mailto: link in https://case.dev.unee-t.com/ & https://unee-t.com/contact-support/

I'm also ignoring the fact on the form you probably didn't verify the email address.

**Comment by franck-boullier** [comment]
Level of spam on support mailbox is low.
Closing this for now

**Comment by kiatlim** [comment]
Sorry I'm late into the picture in chiming in on this. Where is the user submitting feedback? From MEFE directly? Or from the Wordpress site?

If we want the user to provide us with information in a structured way e.g. browser info, uploading of screenshots etc then having a form would be helpful. The experience is perceived as more seamless in the sense that user are seeing it within the same application and they don't have to exit their browser. Using a form also allows us to provide an acknowledgement message to the user (and of course also an email), which provides acknowledgement 1 step earlier than email.

If the user are already filling in feedback from MEFE directly, we should be able to use their name / email to pre-fill the form and they just need to tell us the issue they are facing? So long our fields are kept to a minimal, such as 3 or 4, using form should be an ok approach.

**Downside of using mailto**
Using mailto approach on Android phones  may trigger the "Perform this action with: [select app]". While it is also as easy in the sense that they are just typing straight in the mailbox, the only downside is it doesn't provide a structured way of collecting information. 

**Downside of using form**
Collecting information in a structured way requires effort on the user and may not be ideal, especially if we have a lot of fields to fill in. Users tend to go "Damn, so many fields, so troublesome" and that is what triggers drop offs.

**My take**
If we need to collect structured information, go with the form, if we don't need it right away, a simple form that has seamless experience and acknowledgement should be better than a mailto. But honestly, no harm providing both since it will eventually go in the same place in Helpscout. 

Spam is never taken into consideration in the above argument as I trust that emails will be piped through a central place which handles the spam management.

**For future considerations**
More and more we're seeing such help / support requests moving away from support tickets to chat interfaces, such as Zendesk, Intercom, however these comes at a cost, perhaps something to consider in the long term.
