### ISSUE TITLE
'Assigned to Me' filter is missing on the Unit view of cases

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#364]
In the Unit view in the MEFE (.../unit/xxx) the 'Assigned to Me' filter is missing

![image](https://user-images.githubusercontent.com/31331637/42358545-b040d762-810f-11e8-8f4b-e35156af326d.png)

**Comment by sophieyang0813** [comment]
@nbiton Evening! How can I make available `assignee` in caseList in unit.jsx? I referred to case-explorer.jsx that already exposes `assignee` in caseList. However, the code only allowed me to access metaData, not `assignee` in particular. 

I also experimented in api.cases.js with `${casesCollName}.byUnitName` since this method was subscribed in unit.jsx. I added 'assignee' to `include_fields: 'product,summary,id,status,severity'`.  But this was not the correct approach.  

**case-explorer.jsx** : caseItem includes assignee 
![image](https://user-images.githubusercontent.com/25441733/43515213-8c3f2990-95b4-11e8-98b0-c30f4caffeac.png)

**unit.jsx**: caseItem does not include assignee 
![image](https://user-images.githubusercontent.com/25441733/43515355-db7c9042-95b4-11e8-9505-599a6d1bb586.png)

Another quick question. Would you recommend `memoizeOne` in unit.jsx as I see in `makeCaseGrouping` in case-explorer? or is this extraneous given memoizeOne will only include filtered cases without additional complexities like notifications?  

Thank you!

**Comment by nbiton** [comment]
@sophieyang0813 good evening. 
You'll need to add 'assigned_to' to this line https://github.com/unee-t/frontend/blob/master/imports/api/cases.js#L192
This is the data publication used for cases in unit.jsx

**Comment by nbiton** [comment]
Ok, I understand you might've already tried something similar... but you might not have used the right property name. I'm not sure why it won't work otherwise

**Comment by nbiton** [comment]
`memoizeOne` is used in scenario where a relative complex computed value needs to be generated for rendering the component. Instead of generating it on each render, the usage of of `memoizeOne` makes sure it is recomputed only when the properties it is dependent on change.
