### ISSUE TITLE
Notification missing one case update...

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#390]
# Objective of the test:
Check that the notification mechanism is working expected

# The test:
- As Leonel create go to a case and add
  - 3 new comments
  - 1 new solution
  - 1 new next step

## Expected result:
- Unit is highlighted
- Notification displayed:
  - 3 new messages
  - 2 other changes

## Actual result:
- Unit is highlighted PASSED
- Notification displayed: 
  - 3 new messages PASSED 
  - 1 other changes (1 change is missing) PARTIAL PASS

![image](https://user-images.githubusercontent.com/31331637/42730213-8a3cd142-8821-11e8-94c7-0c1aaa0300fb.png)

**Comment by nbiton** [comment]
"Solution" is not currently a part of the white list of values that MEFE responds to...

The fix is to add it to this list.
One of the reasons it is out of that list is that the possible values for "updated_what" on the message payloads don't match the actual case field names which is why a separate manual mapping was created.
