### ISSUE TITLE
Make Inspection Reports more accessible

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#431]
# The Problem

Today, in order for a user to access Inspection Reports user has to go to Unit >> pick a unit >> got to the IR tab.
This is not intuitive/obvious ---> We need to make IR more visible.

# Suggested solution:

Add a menu item `Inspection Reports` in the Unee-T navigation
![image](https://user-images.githubusercontent.com/31331637/43815673-6c850580-9b03-11e8-8ef9-b273e5fcf622.png)

When user clicks on the `Inspection Reports` Link, user is brought to a page which is similar to the 'Case' page.
That page allows the user to list or create IR in the same way he/she can create a case in a unit

![image](https://user-images.githubusercontent.com/31331637/43815734-c23777d8-9b03-11e8-996a-76155b2a0420.png)

@kiatlim let me know is you have any issue with this design.
Idea: in order to visually differentiate `Cases` from `Inspection Reports` maybe we can use a slightly different color for the header background, what do you recommend?

**Comment by kiatlim** [comment]
@franck-boullier the design is fine and flow is fine.
For header color, we currently don't have different header colors for different "types" of content, so I suggest to just stick with the blue first.

**Comment by franck-boullier** [comment]
> For header color, we currently don't have different header colors for different "types" of content, so I suggest to just stick with the blue first.

@kiatlim OK noted we'll use the current blue first.
We should think of a color scheme for future version though, we'll have:
- the existing page for Cases (list of cases by units
- the page for Inspection Reports (list of inspection reports by units)
- the page for Inventories (list of items by units)

**Comment by sophieyang0813** [comment]
@nbiton Good evening! What do you think about using a higher order component for report-explorer?

 I read several articles about higher order component(hoc) today, since case-explorer and report-explorer share a lot of commonalities. I tried to implement report-explorer by mimicking examples from articles mentioned below. I created hoc function(withExplorer) with common methods seen in case explorer (i.e. handleStatusClicked). I call withExplorer with report function that would render open/closed/assignToMeFilter reports. I felt stuck when trying to add makeCaseGroup that includes open/closed/assignedToMeFilter, since this also includes other params(i.e. allNotifs) irrelevant to report explorer. I am happy to continue experimenting and I also want to check with you if you are okay with this approach 😄😄  

Some of the articles that I referred to: 
1. [Introduction](https://code.tutsplus.com/tutorials/a-gentle-introduction-to-higher-order-components-in-react--cms-30094)
2. [Learn by example](https://code.tutsplus.com/tutorials/a-gentle-introduction-to-hoc-in-react-learn-by-example--cms-30185)
3. [Higher order components in depth](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e)
4.[React official documentation ](https://reactjs.org/docs/higher-order-components.html)

Thank you!

**Comment by nbiton** [comment]
> Edit: No worries! I decided to get the basic working first and then think about DRY principle smilesmile

That sounds like a good approach :smile: 
There are a few patterns in which code reuse can be facilitated.
A higher order component is a pretty good idea, but you can also break down the existing case-explorer to components you can reuse in the report-explorer. 
A pattern for reuse I employed elsewhere, is a generic component that has "renderer functions" provided to the component as props. You can take invite-dialog.jsx as a reference to how that pattern is used. I think it might be suitable for the type of reuse you're trying to make, without the complexity overhead of a higher-order component (although I think it would be great either way).

**Comment by franck-boullier** [comment]
Fixed in the latest version of the PR
