### ISSUE TITLE
iPhone - Inspection Report - Preview is not refreshed

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#522]
# The Problem:

On an iPhone
- Go to inspection report / Draft
- Select an inspection report (IR 1)
- Click on preview
- The preview for IR 1 is generated and visible
- Exit (back)
- Select a Different inspection report (IR 2)
- Click on Preview
- The preview for IR 2 is NOT displayed, the preview that is displayed is the preview for IR 1

**Comment by nbiton** [comment]
@kaihendry The returned URL for the preview html file is the same across multiple reports. So I guess that means that when a preview is requested it overrides the previous file.
I can work around the caching issue using a dummy unique query param on every preview, so that Safari would always serve it from the URL and not cache, but I'm worried the current file overriding flow might cause other issues.
Example scenario: 2 users are trying to access 2 different report previews:

User 1: 
Request preview 1 -> writes html 1 -> "URL" sent to client  -> iframe loads URL -> **html 2** is rendered

User 2:
Request preview 2 -----> writes preview 2 -> "URL" sent to client -> iframe loads URL -> **html 2** is rendered

Can you see what the problem would be?

**Comment by nbiton** [comment]
I just tested my hypothesis... it actually happens! :scream: 

### Actual result
![screenshot from 2018-09-20 15-13-26](https://user-images.githubusercontent.com/2662819/45801875-ceee6f80-bce7-11e8-9bbf-5fb3de5d0b02.png)

### Expected result
![screenshot from 2018-09-20 15-14-42](https://user-images.githubusercontent.com/2662819/45801912-eb8aa780-bce7-11e8-94f1-b7e45d851555.png)
