### ISSUE TITLE
User can't access newly created unit

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#792]
After creating a unit, the user is directed to view it, but only sees an infinite preloader animation and an error in the dev console.

![Screenshot from 2019-05-22 17-50-28](https://user-images.githubusercontent.com/2662819/58165363-3535f280-7cba-11e9-8727-2a7016bd18f6.png)

**Comment by nbiton** [comment]
This doesn't seem to be affecting prod currently. The issue was reproduced on dev.

**Comment by nbiton** [comment]
The user can't fetch the unit's product from BZ API, which causes this error.
The invite lambda needs to be checked to see if it's setting the user's product access rights properly.

@kaihendry can you verify?

**Comment by kaihendry** [comment]
My invite refactor broke this. Still I need Meteor to tell me what's wrong else it's pretty hard to fix.

I want to refactor invite so it just do the queue instead of the POST / push style. I.e. streamline how it works so I can drop some code and make it easier to fathom.

When you get time, be good to chat about this.
