### ISSUE TITLE
CRITICAL No Automated routing from http to https

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#794]
# The problem:

A user that goes to `http://case.unee-t.com`  is not automatically routed to `https://case.unee-t.com`

# Why is this critical:

If a user types `case.unee-t.com` in his/her browser, the user expect to be logged in automatically.
This will NOT happen if the user has entered his/her credentials in `http://case.unee-t.com` and this user is for some reason routed to a url like `https://case.unee-t.com/xxx`

**Comment by kaihendry** [comment]
I asked @nbiton to remove the force-ssl https://github.com/unee-t/frontend/commit/2399c4c3aeecedde0c6171fc91e0bf6cf632404f so that I could test CloudFront in front of dev.

http://case.dev.unee-t.com does correctly redirect to SSL. I think we can safely say CloudFront in front of case works OK, so I will do the same for production.

**Comment by kaihendry** [comment]
Fixed via CloudFront

```
[hendry@t480s ~]$ curl -i http://case.unee-t.com
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Wed, 22 May 2019 13:17:43 GMT
Content-Type: text/html
Content-Length: 183
Connection: keep-alive
Location: https://case.unee-t.com/
X-Cache: Redirect from cloudfront
Via: 1.1 aa0f507eb11fe6a0d0b6bc93ffd294fb.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 4AZOorznLPFqhDXRrPMMlpHeigEk7WjYJjfM85axtViGPA8gCxCXpg==

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```
