### ISSUE TITLE
BUG Floor plan not available when creating a new case

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#878]
# The problem:

- Add a floor plan to a unit
- Create a case

## Expected result:

The floor plan is visible so we can pin the location of the case on the floor plan

## Actual result:

The Floor plan in NOT visible when we create a case.

# The screencast: 

https://media.dev.unee-t.com/2019-09-18/BUG%20-%20Floor%20plan%20not%20visible.mp4

**Comment by kaihendry** [comment]
So this [works on DEV](https://s.natalian.org/2019-09-18/1568777479_2560x1440.png) https://case.dev.unee-t.com/ but not on PROD https://case.unee-t.com/

The version between dev and prod are different: https://version.dev.unee-t.com/

I can see https://travis-ci.org/unee-t/frontend/jobs/585509659 failed because of `Script failed with status 127`. I am not sure what that means, but I am working on it.

**Comment by kaihendry** [comment]
Fixed by deploying manually to Prod. I raised an issue with Travis.
